-- What is the Average cost for each category
SELECT
category,
AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC


-- What is the total revenue for each category
SELECT
P.category,
SUM(S.sales_amount) AS total_revenue,
ROUND(CAST(SUM(S.sales_amount)AS FLOAT) * 100 / SUM(SUM(S.sales_amount)) OVER(), 2) AS sales_percentage
FROM gold.fact_sales S
LEFT JOIN gold.dim_products P ON P.product_key = S.product_key
GROUP BY P.category
ORDER BY total_revenue DESC


-- What is the total revenue generated by each customer
SELECT
C.customer_key,
C.first_name,
C.last_name,
SUM(S.sales_amount) AS total_revenue
FROM gold.fact_sales S
LEFT JOIN gold.dim_customers C ON C.customer_key = S.customer_key 
GROUP BY C.customer_key, C.first_name, C.last_name
ORDER BY total_revenue DESC


-- What is the distribution of sold items across countries
SELECT
C.country,
SUM(S.quantity) AS total_sold_items
FROM gold.fact_sales S
LEFT JOIN gold.dim_customers C ON C.customer_key = S.customer_key 
GROUP BY C.country
ORDER BY total_sold_items DESC
